### ISSUE TITLE
reporte de practica de DLL

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Nayee123#2]
[Reporte_2_Librerias_DLL_Nayeli_Anai_Gonzalez_Lopez.pdf](https://github.com/SistemasTecTlaxiaco/practica-en-dll-en-c-en-visual-studio-Nayee123/files/6340360/Reporte_2_Librerias_DLL_Nayeli_Anai_Gonzalez_Lopez.pdf)

**Comment by Valentiin01** [comment]
tienes 20

**Comment by josealfredo79** [comment]
bien hecho y revisado
